modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "epfragments73"
version = "2.0.0"
displayName = "Fragments Of The Final Gate"
description = '''
        Adds multiple variants of End Portal Frames with unique eyes.
    '''

[[dependencies.epfragments73]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.epfragments73]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "epfragments73.mixins.json"